### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by l0g4n1337** [Alec1017/discord-translator#1]
Hello,
I was looking for a bot to automatically translate anything English or other into Italian.
I'd say your bot does just what I need to do.
Unfortunately I can't get it to work.
(I'm not a programmer) and I get these errors.

$ python run.py
Traceback (most recent call last):
  File "C:\Users\Luigi\Desktop\discord-translator-master\run.py", line 9, in <module>
    discordTranslator.load_initial_messages()
  File "mypath\discord-translator-master\app\translator.py", line 99, in load_initial_messages
    self._display_message(message)
  File "mypath\discord-translator-master\app\translator.py", line 45, in _display_message  
    username = message['author']['username']
TypeError: string indices must be integers

**Comment by Alec1017** [comment]
Hey! glad you're trying out my translator, have you followed all the steps to get started? Including getting the session token?

**Comment by Alec1017** [comment]
Also, i pushed an update to the code to allow for easy translating to and from any language, which should hopefully make it easier for you to translate from english into italian

**Comment by l0g4n1337** [comment]
Nothing to do, I uninstalled python, downloaded the latest version, checked the path, on vs code when I select git bash it doesn't take me python3 or other commands to start venv.
I'm using Windows 11.
I also tried replit but I have the same problems.
Tomorrow I calmly try to figure out how to solve.

--------------------------------------------------------------------------------------------------------------------------------

anyways on replit I can use those commands, I added the secrets (I am the replacement of the .env files) but I still get this error.

~/discord-translator$ source venv/bin/activate
(venv) ~/discord-translator$ python run.py
Traceback (most recent call last):
  File "run.py", line 10, in <module>
    discordTranslator.load_realtime_messages()
  File "/home/runner/discord-translator/app/translator.py", line 107, in load_realtime_messages
    response_content = response['d']
TypeError: 'NoneType' object is not subscriptable

If possible, could you add in the readme how to host it on replit / heroku?
It would be much better for me, all the bots on my server are hosted there, while on vs code I would have to leave my pc always on.
